PREFIX puro: <http://lod2-dev.vse.cz/ontology/puro#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?uri ?valuation ?from ?to ?toType ?fromType ?label ?type  WHERE 
{
  ?uri a puro:BRelation . 
  ?from puro:linkedTo ?uri .
  ?uri puro:linkedTo ?to .
  ?uri rdfs:label ?label . 
  ?uri a ?type .
  OPTIONAL {?uri puro:linkedTo ?valuation. ?valuation a puro:BValuation} 
  FILTER NOT EXISTS{?to a puro:BAttribute}
  FILTER NOT EXISTS{?from a puro:BAttribute}
  FILTER NOT EXISTS{?to a puro:BValuation}
  FILTER NOT EXISTS{?from a puro:BValuation}
  ?to a ?toType . 
  ?from a ?fromType .
}`;